documents:
  - apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: &app_name <%=deployment.name%>
    spec: &default_spec
      replicas: <%=deployment.replicas%>
      selector:
        matchLabels:
          name: *app_name
      strategy:
        type: RollingUpdate
        rollingUpdate:
          maxSurge: 1
          maxUnavailable: 1
      minReadySeconds: 5
      template:
        metadata:
          labels:
            name: *app_name
        spec: &template_spec
          containers:
            - &app_container
              image: '<%=continuous_deployment.image_name%>:latest'
              name: *app_name
              import_secrets: ['secrets.yml', '<%=secrets.name%>']
              ports:
                - containerPort: &port 3000
                  name: '<%=service.backend_port_name%>'

              <% if deployment.liveness_path %>
              livenessProbe: &liveness_probe
                httpGet:
                  path: <%=deployment.liveness_path%>
                  port: *port
                initialDelaySeconds: 50
                timeoutSeconds: 3
                periodSeconds: 15
              readinessProbe: *liveness_probe
              <% end %>

              volumeMounts:
                - &log_volume
                  name: applog
                  mountPath: /app/log

            - &cloudsql_container
              image: gcr.io/cloudsql-docker/gce-proxy:1.09 # Cloud sql proxy
              name: cloudsql-proxy
              command: ["/cloud_sql_proxy", "--dir=/cloudsql",
                        "-instances=<%=deployment.cloud_sql_instance%>",
                        "-credential_file=/secrets/cloudsql/credentials.json"]
              volumeMounts:
                - name: cloudsql-creds
                  mountPath: /secrets/cloudsql
                  readOnly: true

            - &logs_container # print to stdout all log files
              name: print-logs
              image: busybox
              command: [/bin/sh, -c, 'until find log/*.log; do sleep 1; done; tail -n+1 -f log/*.log']
              volumeMounts:
                - *log_volume

          volumes:
            - name: cloudsql-creds
              secret:
                secretName: '<%=deployment.cloud_secret_name%>'
            - name: applog
              emptyDir: {}

  <% if deployment.job_name %>
  - apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: &job_app_name <%=deployment.job_name%>
    spec:
      <<: *default_spec
      replicas: 1
      selector:
        matchLabels:
          name: *job_app_name
      template:
        metadata:
          labels:
            name: *job_app_name
        spec:
          <<: *template_spec
          containers:
            - <<: *app_container
              name: *job_app_name
              command: "/bin/bash -c <%= deployment.job_command %>"
              ports: []

              <%= deployment.job_services.any? %>
              livenessProbe: &liveness_probe
                exec:
                  command: [ /bin/sh, -c,
                    'if [ $(ps -ef | grep "<%= deployment.job_services.join("\|") %>" | grep -v "grep" | wc -l) -lt <%= deployment.job_services.count %> ]; then
                      echo "Some required services are not running"; exit 1;
                    fi' ]
                initialDelaySeconds: 120
                periodSeconds: 30
              readinessProbe: *liveness_probe
              <% end %>

            - *cloudsql_container
            - <<: *logs_container
  <% end %>
