# Every Value has to be base64 encoded
apiVersion: v1
kind: Secret
metadata:
  name: '#{secrets.name}'
type: Opaque
data:
  my_key: "based_64_value_encoded"
  my_key2: "IMPORTANT: For security reason, never ever commit secret values, only keys"